# Generated by Django 4.1.4 on 2024-05-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('member', 'member'), ('guest', 'guest')], max_length=50)),
                ('discribtion', models.TextField()),
                ('userMail', models.EmailField(max_length=254, unique=True)),
                ('userPhone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField(auto_created=True)),
                ('postName', models.CharField(max_length=100)),
                ('postDiscribtion', models.TextField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
